apitrace: Update to latest version
Update apitrace to latest version available in git. This fixes remote
replay using apitrace replay / eglretrace / qapitrace. For details on
remote tracing, see docs/USAGE.markdown, section Advanced GUI usage .

Note that due to configuration of waffle, which might enable multiple
platforms, it is possible to trigger the following error with apitrace
replay / eglretrace:
  error: waffle_display_connect failed
To select a platform for waffle, export WAFFLE_PLATFORM env variable.
Available platforms are e.g. "gbm" or "wayland" and possibly others,
depending on the configuration.

Also note that qapitrace --remote-target launches eglretrace via ssh,
so it is necessary to make sure WAFFLE_PLATFORM env variable is set
there as well.

Signed-off-by: Marek Vasut <marex@denx.de>